/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileCreateRouteImport } from './routes/profile.create'
import { Route as CampaignAddressRouteImport } from './routes/campaign.$address'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCreateRoute = ProfileCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ProfileRoute,
} as any)
const CampaignAddressRoute = CampaignAddressRouteImport.update({
  id: '/campaign/$address',
  path: '/campaign/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/profile': typeof ProfileRouteWithChildren
  '/campaign/$address': typeof CampaignAddressRoute
  '/profile/create': typeof ProfileCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/profile': typeof ProfileRouteWithChildren
  '/campaign/$address': typeof CampaignAddressRoute
  '/profile/create': typeof ProfileCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/profile': typeof ProfileRouteWithChildren
  '/campaign/$address': typeof CampaignAddressRoute
  '/profile/create': typeof ProfileCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/profile'
    | '/campaign/$address'
    | '/profile/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/profile' | '/campaign/$address' | '/profile/create'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/profile'
    | '/campaign/$address'
    | '/profile/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  CampaignAddressRoute: typeof CampaignAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/create': {
      id: '/profile/create'
      path: '/create'
      fullPath: '/profile/create'
      preLoaderRoute: typeof ProfileCreateRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/campaign/$address': {
      id: '/campaign/$address'
      path: '/campaign/$address'
      fullPath: '/campaign/$address'
      preLoaderRoute: typeof CampaignAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileCreateRoute: typeof ProfileCreateRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileCreateRoute: ProfileCreateRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  ProfileRoute: ProfileRouteWithChildren,
  CampaignAddressRoute: CampaignAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
