[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
crowdfunding = "3qUXqi2J3W9juVRqZNrwjpH9WPfzx8wHaPAboXVJVPpp"

[programs.localnet]
crowdfunding = "CYHkx1NUFKahYj4esTR6iuk5MnTZgCKsxufbD2cdK94k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec jest --runInBand --verbose"
